import type { Metadata } from "next";
import "@gov-design-system-ce/styles/lib/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body>
        {/* Needed to correctly load icons from design system components */}
        {/* TODO: Find out if there is a better place to configure it */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.GOV_DS_CONFIG = { iconsPath: "/icons" }`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
